const constants = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGNUP_PROCESSING: 'SIGNUP_PROCESSING',
  SIGNUP_SUCCESSFUL: 'SIGNUP_SUCCESSFUL',
  SIGNUP_UNSUCCESSFUL: 'SIGNUP_UNSUCCESSFUL'
};

export default constants;
