const constants = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  PROCESSING: 'PROCESSING',
  SIGNUP_SUCCESSFUL: 'SIGNUP_SUCCESSFUL',
  PROCESSING_FAILED: 'PROCESSING_FAILED'
};

export default constants;
